### PR TITLE
style: fix header animation to not be jumpy

### LINKED ISSUE #346: App jiggles in certain situations
Jiggle occurs on second monitor in Brave when the browser is more "square". Does not happen on mainMac screen,
https://user-images.githubusercontent.com/30149603/229374087-7dd6492f-3000-4df7-9ee3-72176099838a.mov

### PR DESCRIPTION
**Pull request by vojtechsimetka**
Resolves #346

@sugarpusher please check this.

- There is probably a problem with the left & right spacing of buttons on the header. I was not sure how to fix it, there is some `inset`.

### CODE REVIEW

File: packages/ui/src/lib/components/header.svelte [hunk 1]
```diff
@@ -35,10 +50,20 @@
...
+{/if}
 
 <style lang="scss">
 	header.root {
-		position: sticky;
+		position: fixed;
+		top: 0;
+		left: 0;
+		right: 0;
 		inset: 0 -10px auto;
```
Comment (sugarpusher) [inline packages/ui/src/lib/components/header.svelte:67]:
```suggestion
		inset: 0 0 auto;
```

**Comment by sugarpusher** [comment]
Yup I had to use some css acrobatics before which I think may no longer be necessary after your changes. Changing the inset should fix it.
